# Generated by Django 3.2.11 on 2022-09-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('politics', 'Politics'), ('technology', 'Technology'), ('literature', 'Literature'), ('economy', 'Economy'), ('health', 'Health')], max_length=51, null=True),
        ),
    ]
