# Generated by Django 3.2.11 on 2022-09-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='image',
        ),
    ]
