# Generated by Django 3.2.11 on 2022-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_rename_cover_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=9501, null=True),
        ),
    ]
